<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerICXzOXw\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerICXzOXw/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerICXzOXw.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerICXzOXw\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerICXzOXw\srcApp_KernelProdContainer([
    'container.build_hash' => 'ICXzOXw',
    'container.build_id' => '92635269',
    'container.build_time' => 1569597307,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerICXzOXw');
